-- Seed the normalized catalog from MapLov's validated legacy choices, then
-- associate existing text profiles/preferences with normalized identifiers.

begin;

insert into public.countries(name, iso2)
values
  ('Afghanistan', 'AF'),
  ('Albania', 'AL'),
  ('Algeria', 'DZ'),
  ('Andorra', 'AD'),
  ('Angola', 'AO'),
  ('Antigua and Barbuda', 'AG'),
  ('Argentina', 'AR'),
  ('Armenia', 'AM'),
  ('Australia', 'AU'),
  ('Austria', 'AT'),
  ('Azerbaijan', 'AZ'),
  ('Bahamas', 'BS'),
  ('Bahrain', 'BH'),
  ('Bangladesh', 'BD'),
  ('Barbados', 'BB'),
  ('Belarus', 'BY'),
  ('Belgium', 'BE'),
  ('Belize', 'BZ'),
  ('Benin', 'BJ'),
  ('Bhutan', 'BT'),
  ('Bolivia', 'BO'),
  ('Bosnia and Herzegovina', 'BA'),
  ('Botswana', 'BW'),
  ('Brazil', 'BR'),
  ('Brunei', 'BN'),
  ('Bulgaria', 'BG'),
  ('Burkina Faso', 'BF'),
  ('Burundi', 'BI'),
  ('Cabo Verde', 'CV'),
  ('Cambodia', 'KH'),
  ('Cameroon', 'CM'),
  ('Canada', 'CA'),
  ('Central African Republic', 'CF'),
  ('Chad', 'TD'),
  ('Chile', 'CL'),
  ('China', 'CN'),
  ('Colombia', 'CO'),
  ('Comoros', 'KM'),
  ('Congo', 'CG'),
  ('Costa Rica', 'CR'),
  ('Côte d’Ivoire', 'CI'),
  ('Croatia', 'HR'),
  ('Cuba', 'CU'),
  ('Cyprus', 'CY'),
  ('Czechia', 'CZ'),
  ('Democratic Republic of the Congo', 'CD'),
  ('Denmark', 'DK'),
  ('Djibouti', 'DJ'),
  ('Dominica', 'DM'),
  ('Dominican Republic', 'DO'),
  ('Ecuador', 'EC'),
  ('Egypt', 'EG'),
  ('El Salvador', 'SV'),
  ('Equatorial Guinea', 'GQ'),
  ('Eritrea', 'ER'),
  ('Estonia', 'EE'),
  ('Eswatini', 'SZ'),
  ('Ethiopia', 'ET'),
  ('Fiji', 'FJ'),
  ('Finland', 'FI'),
  ('France', 'FR'),
  ('Gabon', 'GA'),
  ('Gambia', 'GM'),
  ('Georgia', 'GE'),
  ('Germany', 'DE'),
  ('Ghana', 'GH'),
  ('Greece', 'GR'),
  ('Grenada', 'GD'),
  ('Guatemala', 'GT'),
  ('Guinea', 'GN'),
  ('Guinea-Bissau', 'GW'),
  ('Guyana', 'GY'),
  ('Haiti', 'HT'),
  ('Honduras', 'HN'),
  ('Hungary', 'HU'),
  ('Iceland', 'IS'),
  ('India', 'IN'),
  ('Indonesia', 'ID'),
  ('Iran', 'IR'),
  ('Iraq', 'IQ'),
  ('Ireland', 'IE'),
  ('Israel', 'IL'),
  ('Italy', 'IT'),
  ('Jamaica', 'JM'),
  ('Japan', 'JP'),
  ('Jordan', 'JO'),
  ('Kazakhstan', 'KZ'),
  ('Kenya', 'KE'),
  ('Kiribati', 'KI'),
  ('Kuwait', 'KW'),
  ('Kyrgyzstan', 'KG'),
  ('Laos', 'LA'),
  ('Latvia', 'LV'),
  ('Lebanon', 'LB'),
  ('Lesotho', 'LS'),
  ('Liberia', 'LR'),
  ('Libya', 'LY'),
  ('Liechtenstein', 'LI'),
  ('Lithuania', 'LT'),
  ('Luxembourg', 'LU'),
  ('Madagascar', 'MG'),
  ('Malawi', 'MW'),
  ('Malaysia', 'MY'),
  ('Maldives', 'MV'),
  ('Mali', 'ML'),
  ('Malta', 'MT'),
  ('Marshall Islands', 'MH'),
  ('Mauritania', 'MR'),
  ('Mauritius', 'MU'),
  ('Mexico', 'MX'),
  ('Micronesia', 'FM'),
  ('Moldova', 'MD'),
  ('Monaco', 'MC'),
  ('Mongolia', 'MN'),
  ('Montenegro', 'ME'),
  ('Morocco', 'MA'),
  ('Mozambique', 'MZ'),
  ('Myanmar', 'MM'),
  ('Namibia', 'NA'),
  ('Nauru', 'NR'),
  ('Nepal', 'NP'),
  ('Netherlands', 'NL'),
  ('New Zealand', 'NZ'),
  ('Nicaragua', 'NI'),
  ('Niger', 'NE'),
  ('Nigeria', 'NG'),
  ('North Korea', 'KP'),
  ('North Macedonia', 'MK'),
  ('Norway', 'NO'),
  ('Oman', 'OM'),
  ('Pakistan', 'PK'),
  ('Palau', 'PW'),
  ('Palestine', 'PS'),
  ('Panama', 'PA'),
  ('Papua New Guinea', 'PG'),
  ('Paraguay', 'PY'),
  ('Peru', 'PE'),
  ('Philippines', 'PH'),
  ('Poland', 'PL'),
  ('Portugal', 'PT'),
  ('Qatar', 'QA'),
  ('Romania', 'RO'),
  ('Russia', 'RU'),
  ('Rwanda', 'RW'),
  ('Saint Kitts and Nevis', 'KN'),
  ('Saint Lucia', 'LC'),
  ('Saint Vincent and the Grenadines', 'VC'),
  ('Samoa', 'WS'),
  ('San Marino', 'SM'),
  ('São Tomé and Príncipe', 'ST'),
  ('Saudi Arabia', 'SA'),
  ('Senegal', 'SN'),
  ('Serbia', 'RS'),
  ('Seychelles', 'SC'),
  ('Sierra Leone', 'SL'),
  ('Singapore', 'SG'),
  ('Slovakia', 'SK'),
  ('Slovenia', 'SI'),
  ('Solomon Islands', 'SB'),
  ('Somalia', 'SO'),
  ('South Africa', 'ZA'),
  ('South Korea', 'KR'),
  ('South Sudan', 'SS'),
  ('Spain', 'ES'),
  ('Sri Lanka', 'LK'),
  ('Sudan', 'SD'),
  ('Suriname', 'SR'),
  ('Sweden', 'SE'),
  ('Switzerland', 'CH'),
  ('Syria', 'SY'),
  ('Taiwan', 'TW'),
  ('Tajikistan', 'TJ'),
  ('Tanzania', 'TZ'),
  ('Thailand', 'TH'),
  ('Timor-Leste', 'TL'),
  ('Togo', 'TG'),
  ('Tonga', 'TO'),
  ('Trinidad and Tobago', 'TT'),
  ('Tunisia', 'TN'),
  ('Türkiye', 'TR'),
  ('Turkmenistan', 'TM'),
  ('Tuvalu', 'TV'),
  ('Uganda', 'UG'),
  ('Ukraine', 'UA'),
  ('United Arab Emirates', 'AE'),
  ('United Kingdom', 'GB'),
  ('United States', 'US'),
  ('Uruguay', 'UY'),
  ('Uzbekistan', 'UZ'),
  ('Vanuatu', 'VU'),
  ('Vatican City', 'VA'),
  ('Venezuela', 'VE'),
  ('Vietnam', 'VN'),
  ('Yemen', 'YE'),
  ('Zambia', 'ZM'),
  ('Zimbabwe', 'ZW')
on conflict do nothing;

with source(country_name, region_name) as (
  values
  ('Canada', 'Alberta'),
  ('Canada', 'British Columbia'),
  ('Canada', 'Manitoba'),
  ('Canada', 'New Brunswick'),
  ('Canada', 'Newfoundland and Labrador'),
  ('Canada', 'Northwest Territories'),
  ('Canada', 'Nova Scotia'),
  ('Canada', 'Nunavut'),
  ('Canada', 'Ontario'),
  ('Canada', 'Prince Edward Island'),
  ('Canada', 'Quebec'),
  ('Canada', 'Saskatchewan'),
  ('Canada', 'Yukon'),
  ('United States', 'California'),
  ('United States', 'Florida'),
  ('United States', 'Georgia'),
  ('United States', 'Illinois'),
  ('United States', 'Massachusetts'),
  ('United States', 'Michigan'),
  ('United States', 'New Jersey'),
  ('United States', 'New York'),
  ('United States', 'North Carolina'),
  ('United States', 'Ohio'),
  ('United States', 'Pennsylvania'),
  ('United States', 'Texas'),
  ('United States', 'Virginia'),
  ('United States', 'Washington'),
  ('Cameroon', 'Adamawa'),
  ('Cameroon', 'Centre'),
  ('Cameroon', 'East'),
  ('Cameroon', 'Far North'),
  ('Cameroon', 'Littoral'),
  ('Cameroon', 'North'),
  ('Cameroon', 'North-West'),
  ('Cameroon', 'South'),
  ('Cameroon', 'South-West'),
  ('Cameroon', 'West'),
  ('France', 'Auvergne-Rhône-Alpes'),
  ('France', 'Bourgogne-Franche-Comté'),
  ('France', 'Brittany'),
  ('France', 'Centre-Val de Loire'),
  ('France', 'Corsica'),
  ('France', 'Grand Est'),
  ('France', 'Hauts-de-France'),
  ('France', 'Île-de-France'),
  ('France', 'Normandy'),
  ('France', 'Nouvelle-Aquitaine'),
  ('France', 'Occitanie'),
  ('France', 'Pays de la Loire'),
  ('France', 'Provence-Alpes-Côte d’Azur'),
  ('United Kingdom', 'England'),
  ('United Kingdom', 'Northern Ireland'),
  ('United Kingdom', 'Scotland'),
  ('United Kingdom', 'Wales'),
  ('Canada', 'Other region'),
  ('United States', 'Other region'),
  ('Mexico', 'Other region'),
  ('Brazil', 'Other region'),
  ('United Kingdom', 'Other region'),
  ('France', 'Other region'),
  ('Germany', 'Other region'),
  ('Spain', 'Other region'),
  ('Italy', 'Other region'),
  ('Belgium', 'Other region'),
  ('Switzerland', 'Other region'),
  ('Morocco', 'Other region'),
  ('Algeria', 'Other region'),
  ('Tunisia', 'Other region'),
  ('Senegal', 'Other region'),
  ('Cameroon', 'Other region'),
  ('Côte d’Ivoire', 'Other region'),
  ('Democratic Republic of the Congo', 'Other region'),
  ('Nigeria', 'Other region'),
  ('South Africa', 'Other region'),
  ('India', 'Other region'),
  ('China', 'Other region'),
  ('Japan', 'Other region'),
  ('Australia', 'Other region'),
  ('New Zealand', 'Other region')
)
insert into public.regions(country_id, name)
select country.id, source.region_name
from source
join public.countries country
  on lower(btrim(country.name)) = lower(btrim(source.country_name))
on conflict do nothing;

with source(country_name, region_name, city_name) as (
  values
  ('Canada', 'Alberta', 'Airdrie'),
  ('Canada', 'Alberta', 'Calgary'),
  ('Canada', 'Alberta', 'Camrose'),
  ('Canada', 'Alberta', 'Cold Lake'),
  ('Canada', 'Alberta', 'Edmonton'),
  ('Canada', 'Alberta', 'Fort McMurray'),
  ('Canada', 'Alberta', 'Fort Saskatchewan'),
  ('Canada', 'Alberta', 'Grande Prairie'),
  ('Canada', 'Alberta', 'Lacombe'),
  ('Canada', 'Alberta', 'Leduc'),
  ('Canada', 'Alberta', 'Lethbridge'),
  ('Canada', 'Alberta', 'Medicine Hat'),
  ('Canada', 'Alberta', 'Okotoks'),
  ('Canada', 'Alberta', 'Red Deer'),
  ('Canada', 'Alberta', 'Spruce Grove'),
  ('Canada', 'Alberta', 'St. Albert'),
  ('Canada', 'British Columbia', 'Abbotsford'),
  ('Canada', 'British Columbia', 'Burnaby'),
  ('Canada', 'British Columbia', 'Campbell River'),
  ('Canada', 'British Columbia', 'Chilliwack'),
  ('Canada', 'British Columbia', 'Coquitlam'),
  ('Canada', 'British Columbia', 'Courtenay'),
  ('Canada', 'British Columbia', 'Cranbrook'),
  ('Canada', 'British Columbia', 'Delta'),
  ('Canada', 'British Columbia', 'Fort St. John'),
  ('Canada', 'British Columbia', 'Kamloops'),
  ('Canada', 'British Columbia', 'Kelowna'),
  ('Canada', 'British Columbia', 'Langford'),
  ('Canada', 'British Columbia', 'Langley'),
  ('Canada', 'British Columbia', 'Maple Ridge'),
  ('Canada', 'British Columbia', 'Nanaimo'),
  ('Canada', 'British Columbia', 'Nelson'),
  ('Canada', 'British Columbia', 'New Westminster'),
  ('Canada', 'British Columbia', 'North Vancouver'),
  ('Canada', 'British Columbia', 'Parksville'),
  ('Canada', 'British Columbia', 'Penticton'),
  ('Canada', 'British Columbia', 'Port Alberni'),
  ('Canada', 'British Columbia', 'Port Coquitlam'),
  ('Canada', 'British Columbia', 'Port Moody'),
  ('Canada', 'British Columbia', 'Powell River'),
  ('Canada', 'British Columbia', 'Prince George'),
  ('Canada', 'British Columbia', 'Prince Rupert'),
  ('Canada', 'British Columbia', 'Quesnel'),
  ('Canada', 'British Columbia', 'Richmond'),
  ('Canada', 'British Columbia', 'Salmon Arm'),
  ('Canada', 'British Columbia', 'Surrey'),
  ('Canada', 'British Columbia', 'Terrace'),
  ('Canada', 'British Columbia', 'Trail'),
  ('Canada', 'British Columbia', 'Vancouver'),
  ('Canada', 'British Columbia', 'Vernon'),
  ('Canada', 'British Columbia', 'Victoria'),
  ('Canada', 'British Columbia', 'West Kelowna'),
  ('Canada', 'British Columbia', 'White Rock'),
  ('Canada', 'British Columbia', 'Williams Lake'),
  ('Canada', 'Manitoba', 'Brandon'),
  ('Canada', 'Manitoba', 'Dauphin'),
  ('Canada', 'Manitoba', 'Flin Flon'),
  ('Canada', 'Manitoba', 'Morden'),
  ('Canada', 'Manitoba', 'Portage la Prairie'),
  ('Canada', 'Manitoba', 'Selkirk'),
  ('Canada', 'Manitoba', 'Steinbach'),
  ('Canada', 'Manitoba', 'Thompson'),
  ('Canada', 'Manitoba', 'Winkler'),
  ('Canada', 'Manitoba', 'Winnipeg'),
  ('Canada', 'New Brunswick', 'Bathurst'),
  ('Canada', 'New Brunswick', 'Campbellton'),
  ('Canada', 'New Brunswick', 'Dieppe'),
  ('Canada', 'New Brunswick', 'Edmundston'),
  ('Canada', 'New Brunswick', 'Fredericton'),
  ('Canada', 'New Brunswick', 'Miramichi'),
  ('Canada', 'New Brunswick', 'Moncton'),
  ('Canada', 'New Brunswick', 'Saint John'),
  ('Canada', 'Newfoundland and Labrador', 'Corner Brook'),
  ('Canada', 'Newfoundland and Labrador', 'Mount Pearl'),
  ('Canada', 'Newfoundland and Labrador', 'St. John’s'),
  ('Canada', 'Northwest Territories', 'Yellowknife'),
  ('Canada', 'Nova Scotia', 'Dartmouth'),
  ('Canada', 'Nova Scotia', 'Halifax'),
  ('Canada', 'Nova Scotia', 'New Glasgow'),
  ('Canada', 'Nova Scotia', 'Sydney'),
  ('Canada', 'Nunavut', 'Iqaluit'),
  ('Canada', 'Ontario', 'Ajax'),
  ('Canada', 'Ontario', 'Aurora'),
  ('Canada', 'Ontario', 'Barrie'),
  ('Canada', 'Ontario', 'Belleville'),
  ('Canada', 'Ontario', 'Brampton'),
  ('Canada', 'Ontario', 'Brantford'),
  ('Canada', 'Ontario', 'Brockville'),
  ('Canada', 'Ontario', 'Burlington'),
  ('Canada', 'Ontario', 'Cambridge'),
  ('Canada', 'Ontario', 'Chatham-Kent'),
  ('Canada', 'Ontario', 'Clarence-Rockland'),
  ('Canada', 'Ontario', 'Collingwood'),
  ('Canada', 'Ontario', 'Cornwall'),
  ('Canada', 'Ontario', 'Elliot Lake'),
  ('Canada', 'Ontario', 'Greater Sudbury'),
  ('Canada', 'Ontario', 'Guelph'),
  ('Canada', 'Ontario', 'Hamilton'),
  ('Canada', 'Ontario', 'Kawartha Lakes'),
  ('Canada', 'Ontario', 'Kenora'),
  ('Canada', 'Ontario', 'Kingston'),
  ('Canada', 'Ontario', 'Kitchener'),
  ('Canada', 'Ontario', 'London'),
  ('Canada', 'Ontario', 'Markham'),
  ('Canada', 'Ontario', 'Mississauga'),
  ('Canada', 'Ontario', 'Niagara Falls'),
  ('Canada', 'Ontario', 'North Bay'),
  ('Canada', 'Ontario', 'Oakville'),
  ('Canada', 'Ontario', 'Orangeville'),
  ('Canada', 'Ontario', 'Orillia'),
  ('Canada', 'Ontario', 'Oshawa'),
  ('Canada', 'Ontario', 'Ottawa'),
  ('Canada', 'Ontario', 'Owen Sound'),
  ('Canada', 'Ontario', 'Pembroke'),
  ('Canada', 'Ontario', 'Peterborough'),
  ('Canada', 'Ontario', 'Pickering'),
  ('Canada', 'Ontario', 'Quinte West'),
  ('Canada', 'Ontario', 'Richmond Hill'),
  ('Canada', 'Ontario', 'Sarnia'),
  ('Canada', 'Ontario', 'Sault Ste. Marie'),
  ('Canada', 'Ontario', 'St. Catharines'),
  ('Canada', 'Ontario', 'St. Thomas'),
  ('Canada', 'Ontario', 'Stratford'),
  ('Canada', 'Ontario', 'Thunder Bay'),
  ('Canada', 'Ontario', 'Timmins'),
  ('Canada', 'Ontario', 'Toronto'),
  ('Canada', 'Ontario', 'Vaughan'),
  ('Canada', 'Ontario', 'Waterloo'),
  ('Canada', 'Ontario', 'Welland'),
  ('Canada', 'Ontario', 'Windsor'),
  ('Canada', 'Ontario', 'Woodstock'),
  ('Canada', 'Prince Edward Island', 'Charlottetown'),
  ('Canada', 'Quebec', 'Alma'),
  ('Canada', 'Quebec', 'Amos'),
  ('Canada', 'Quebec', 'Blainville'),
  ('Canada', 'Quebec', 'Boisbriand'),
  ('Canada', 'Quebec', 'Boucherville'),
  ('Canada', 'Quebec', 'Brossard'),
  ('Canada', 'Quebec', 'Châteauguay'),
  ('Canada', 'Quebec', 'Côte Saint-Luc'),
  ('Canada', 'Quebec', 'Dollard-des-Ormeaux'),
  ('Canada', 'Quebec', 'Drummondville'),
  ('Canada', 'Quebec', 'Gatineau'),
  ('Canada', 'Quebec', 'Granby'),
  ('Canada', 'Quebec', 'Joliette'),
  ('Canada', 'Quebec', 'Kirkland'),
  ('Canada', 'Quebec', 'La Prairie'),
  ('Canada', 'Quebec', 'Laval'),
  ('Canada', 'Quebec', 'Lévis'),
  ('Canada', 'Quebec', 'Longueuil'),
  ('Canada', 'Quebec', 'Mirabel'),
  ('Canada', 'Quebec', 'Mont-Laurier'),
  ('Canada', 'Quebec', 'Montréal'),
  ('Canada', 'Quebec', 'Québec City'),
  ('Canada', 'Quebec', 'Repentigny'),
  ('Canada', 'Quebec', 'Rimouski'),
  ('Canada', 'Quebec', 'Rivière-du-Loup'),
  ('Canada', 'Quebec', 'Rouyn-Noranda'),
  ('Canada', 'Quebec', 'Saguenay'),
  ('Canada', 'Quebec', 'Saint-Bruno-de-Montarville'),
  ('Canada', 'Quebec', 'Saint-Constant'),
  ('Canada', 'Quebec', 'Saint-Eustache'),
  ('Canada', 'Quebec', 'Saint-Georges'),
  ('Canada', 'Quebec', 'Saint-Hyacinthe'),
  ('Canada', 'Quebec', 'Saint-Jean-sur-Richelieu'),
  ('Canada', 'Quebec', 'Saint-Jérôme'),
  ('Canada', 'Quebec', 'Saint-Lambert'),
  ('Canada', 'Quebec', 'Sainte-Julie'),
  ('Canada', 'Quebec', 'Sept-Îles'),
  ('Canada', 'Quebec', 'Sherbrooke'),
  ('Canada', 'Quebec', 'Terrebonne'),
  ('Canada', 'Quebec', 'Thetford Mines'),
  ('Canada', 'Quebec', 'Trois-Rivières'),
  ('Canada', 'Quebec', 'Val-d’Or'),
  ('Canada', 'Saskatchewan', 'Estevan'),
  ('Canada', 'Saskatchewan', 'Lloydminster'),
  ('Canada', 'Saskatchewan', 'Moose Jaw'),
  ('Canada', 'Saskatchewan', 'Prince Albert'),
  ('Canada', 'Saskatchewan', 'Regina'),
  ('Canada', 'Saskatchewan', 'Saskatoon'),
  ('Canada', 'Saskatchewan', 'Swift Current'),
  ('Canada', 'Yukon', 'Whitehorse'),
  ('United States', 'California', 'Los Angeles'),
  ('United States', 'California', 'San Diego'),
  ('United States', 'California', 'San Francisco'),
  ('United States', 'Florida', 'Miami'),
  ('United States', 'Illinois', 'Chicago'),
  ('United States', 'Massachusetts', 'Boston'),
  ('United States', 'New York', 'New York'),
  ('United States', 'Pennsylvania', 'Philadelphia'),
  ('United States', 'Texas', 'Austin'),
  ('United States', 'Texas', 'Dallas'),
  ('United States', 'Texas', 'Houston'),
  ('United States', 'Texas', 'San Antonio'),
  ('United States', 'Washington', 'Seattle'),
  ('France', 'Auvergne-Rhône-Alpes', 'Lyon'),
  ('France', 'Île-de-France', 'Paris'),
  ('France', 'Nouvelle-Aquitaine', 'Bordeaux'),
  ('France', 'Occitanie', 'Toulouse'),
  ('France', 'Provence-Alpes-Côte d’Azur', 'Marseille'),
  ('France', 'Provence-Alpes-Côte d’Azur', 'Nice'),
  ('United Kingdom', 'England', 'Birmingham'),
  ('United Kingdom', 'England', 'London'),
  ('United Kingdom', 'England', 'Manchester'),
  ('United Kingdom', 'Scotland', 'Edinburgh'),
  ('United Kingdom', 'Scotland', 'Glasgow'),
  ('Cameroon', 'Adamawa', 'Ngaoundéré'),
  ('Cameroon', 'Adamawa', 'Meiganga'),
  ('Cameroon', 'Adamawa', 'Banyo'),
  ('Cameroon', 'Adamawa', 'Tibati'),
  ('Cameroon', 'Adamawa', 'Tignère'),
  ('Cameroon', 'Centre', 'Yaoundé'),
  ('Cameroon', 'Centre', 'Mbalmayo'),
  ('Cameroon', 'Centre', 'Bafia'),
  ('Cameroon', 'Centre', 'Obala'),
  ('Cameroon', 'Centre', 'Mfou'),
  ('Cameroon', 'Centre', 'Nanga-Eboko'),
  ('Cameroon', 'Centre', 'Akonolinga'),
  ('Cameroon', 'Centre', 'Eséka'),
  ('Cameroon', 'Centre', 'Monatélé'),
  ('Cameroon', 'Centre', 'Ntui'),
  ('Cameroon', 'East', 'Bertoua'),
  ('Cameroon', 'East', 'Batouri'),
  ('Cameroon', 'East', 'Yokadouma'),
  ('Cameroon', 'East', 'Abong-Mbang'),
  ('Cameroon', 'East', 'Garoua-Boulaï'),
  ('Cameroon', 'East', 'Bélabo'),
  ('Cameroon', 'East', 'Kétté'),
  ('Cameroon', 'East', 'Lomié'),
  ('Cameroon', 'Far North', 'Maroua'),
  ('Cameroon', 'Far North', 'Kousséri'),
  ('Cameroon', 'Far North', 'Mokolo'),
  ('Cameroon', 'Far North', 'Yagoua'),
  ('Cameroon', 'Far North', 'Mora'),
  ('Cameroon', 'Far North', 'Kaélé'),
  ('Cameroon', 'Far North', 'Bogo'),
  ('Cameroon', 'Far North', 'Maga'),
  ('Cameroon', 'Far North', 'Waza'),
  ('Cameroon', 'Littoral', 'Douala'),
  ('Cameroon', 'Littoral', 'Nkongsamba'),
  ('Cameroon', 'Littoral', 'Edéa'),
  ('Cameroon', 'Littoral', 'Loum'),
  ('Cameroon', 'Littoral', 'Manjo'),
  ('Cameroon', 'Littoral', 'Melong'),
  ('Cameroon', 'Littoral', 'Mbanga'),
  ('Cameroon', 'Littoral', 'Dibombari'),
  ('Cameroon', 'North', 'Garoua'),
  ('Cameroon', 'North', 'Guider'),
  ('Cameroon', 'North', 'Figuil'),
  ('Cameroon', 'North', 'Pitoa'),
  ('Cameroon', 'North', 'Poli'),
  ('Cameroon', 'North', 'Lagdo'),
  ('Cameroon', 'North', 'Touboro'),
  ('Cameroon', 'North', 'Rey-Bouba'),
  ('Cameroon', 'North', 'Tcholliré'),
  ('Cameroon', 'North-West', 'Bamenda'),
  ('Cameroon', 'North-West', 'Kumbo'),
  ('Cameroon', 'North-West', 'Wum'),
  ('Cameroon', 'North-West', 'Nkambe'),
  ('Cameroon', 'North-West', 'Fundong'),
  ('Cameroon', 'North-West', 'Ndop'),
  ('Cameroon', 'North-West', 'Bali'),
  ('Cameroon', 'North-West', 'Bafut'),
  ('Cameroon', 'North-West', 'Batibo'),
  ('Cameroon', 'North-West', 'Mbengwi'),
  ('Cameroon', 'South', 'Ebolowa'),
  ('Cameroon', 'South', 'Kribi'),
  ('Cameroon', 'South', 'Sangmélima'),
  ('Cameroon', 'South', 'Ambam'),
  ('Cameroon', 'South', 'Lolodorf'),
  ('Cameroon', 'South', 'Akom II'),
  ('Cameroon', 'South', 'Djoum'),
  ('Cameroon', 'South', 'Zoétélé'),
  ('Cameroon', 'South', 'Meyomessala'),
  ('Cameroon', 'South-West', 'Buea'),
  ('Cameroon', 'South-West', 'Limbe'),
  ('Cameroon', 'South-West', 'Kumba'),
  ('Cameroon', 'South-West', 'Tiko'),
  ('Cameroon', 'South-West', 'Mamfe'),
  ('Cameroon', 'South-West', 'Muyuka'),
  ('Cameroon', 'South-West', 'Mutengene'),
  ('Cameroon', 'South-West', 'Bangem'),
  ('Cameroon', 'South-West', 'Mundemba'),
  ('Cameroon', 'South-West', 'Tombel'),
  ('Cameroon', 'South-West', 'Ekondo-Titi'),
  ('Cameroon', 'West', 'Bafoussam'),
  ('Cameroon', 'West', 'Dschang'),
  ('Cameroon', 'West', 'Foumban'),
  ('Cameroon', 'West', 'Mbouda'),
  ('Cameroon', 'West', 'Bafang'),
  ('Cameroon', 'West', 'Bangangté'),
  ('Cameroon', 'West', 'Foumbot'),
  ('Cameroon', 'West', 'Bandjoun'),
  ('Cameroon', 'West', 'Baham'),
  ('Cameroon', 'West', 'Tonga'),
  ('Cameroon', 'West', 'Batcham'),
  ('Canada', 'Other region', 'Abbotsford'),
  ('Canada', 'Other region', 'Airdrie'),
  ('Canada', 'Other region', 'Ajax'),
  ('Canada', 'Other region', 'Alma'),
  ('Canada', 'Other region', 'Amos'),
  ('Canada', 'Other region', 'Aurora'),
  ('Canada', 'Other region', 'Barrie'),
  ('Canada', 'Other region', 'Bathurst'),
  ('Canada', 'Other region', 'Belleville'),
  ('Canada', 'Other region', 'Blainville'),
  ('Canada', 'Other region', 'Boisbriand'),
  ('Canada', 'Other region', 'Boucherville'),
  ('Canada', 'Other region', 'Brampton'),
  ('Canada', 'Other region', 'Brandon'),
  ('Canada', 'Other region', 'Brantford'),
  ('Canada', 'Other region', 'Brockville'),
  ('Canada', 'Other region', 'Brossard'),
  ('Canada', 'Other region', 'Burlington'),
  ('Canada', 'Other region', 'Burnaby'),
  ('Canada', 'Other region', 'Calgary'),
  ('Canada', 'Other region', 'Cambridge'),
  ('Canada', 'Other region', 'Campbell River'),
  ('Canada', 'Other region', 'Campbellton'),
  ('Canada', 'Other region', 'Camrose'),
  ('Canada', 'Other region', 'Charlottetown'),
  ('Canada', 'Other region', 'Châteauguay'),
  ('Canada', 'Other region', 'Chatham-Kent'),
  ('Canada', 'Other region', 'Chilliwack'),
  ('Canada', 'Other region', 'Clarence-Rockland'),
  ('Canada', 'Other region', 'Cold Lake'),
  ('Canada', 'Other region', 'Collingwood'),
  ('Canada', 'Other region', 'Coquitlam'),
  ('Canada', 'Other region', 'Corner Brook'),
  ('Canada', 'Other region', 'Cornwall'),
  ('Canada', 'Other region', 'Côte Saint-Luc'),
  ('Canada', 'Other region', 'Courtenay'),
  ('Canada', 'Other region', 'Cranbrook'),
  ('Canada', 'Other region', 'Dartmouth'),
  ('Canada', 'Other region', 'Dauphin'),
  ('Canada', 'Other region', 'Delta'),
  ('Canada', 'Other region', 'Dieppe'),
  ('Canada', 'Other region', 'Dollard-des-Ormeaux'),
  ('Canada', 'Other region', 'Drummondville'),
  ('Canada', 'Other region', 'Edmonton'),
  ('Canada', 'Other region', 'Edmundston'),
  ('Canada', 'Other region', 'Elliot Lake'),
  ('Canada', 'Other region', 'Estevan'),
  ('Canada', 'Other region', 'Flin Flon'),
  ('Canada', 'Other region', 'Fort McMurray'),
  ('Canada', 'Other region', 'Fort Saskatchewan'),
  ('Canada', 'Other region', 'Fort St. John'),
  ('Canada', 'Other region', 'Fredericton'),
  ('Canada', 'Other region', 'Gatineau'),
  ('Canada', 'Other region', 'Grande Prairie'),
  ('Canada', 'Other region', 'Granby'),
  ('Canada', 'Other region', 'Greater Sudbury'),
  ('Canada', 'Other region', 'Guelph'),
  ('Canada', 'Other region', 'Halifax'),
  ('Canada', 'Other region', 'Hamilton'),
  ('Canada', 'Other region', 'Iqaluit'),
  ('Canada', 'Other region', 'Joliette'),
  ('Canada', 'Other region', 'Kamloops'),
  ('Canada', 'Other region', 'Kawartha Lakes'),
  ('Canada', 'Other region', 'Kelowna'),
  ('Canada', 'Other region', 'Kenora'),
  ('Canada', 'Other region', 'Kingston'),
  ('Canada', 'Other region', 'Kirkland'),
  ('Canada', 'Other region', 'Kitchener'),
  ('Canada', 'Other region', 'La Prairie'),
  ('Canada', 'Other region', 'Lacombe'),
  ('Canada', 'Other region', 'Langford'),
  ('Canada', 'Other region', 'Langley'),
  ('Canada', 'Other region', 'Laval'),
  ('Canada', 'Other region', 'Leduc'),
  ('Canada', 'Other region', 'Lethbridge'),
  ('Canada', 'Other region', 'Lévis'),
  ('Canada', 'Other region', 'Lloydminster'),
  ('Canada', 'Other region', 'London'),
  ('Canada', 'Other region', 'Longueuil'),
  ('Canada', 'Other region', 'Maple Ridge'),
  ('Canada', 'Other region', 'Markham'),
  ('Canada', 'Other region', 'Medicine Hat'),
  ('Canada', 'Other region', 'Miramichi'),
  ('Canada', 'Other region', 'Mirabel'),
  ('Canada', 'Other region', 'Mississauga'),
  ('Canada', 'Other region', 'Moncton'),
  ('Canada', 'Other region', 'Mont-Laurier'),
  ('Canada', 'Other region', 'Montréal'),
  ('Canada', 'Other region', 'Moose Jaw'),
  ('Canada', 'Other region', 'Morden'),
  ('Canada', 'Other region', 'Mount Pearl'),
  ('Canada', 'Other region', 'Nanaimo'),
  ('Canada', 'Other region', 'Nelson'),
  ('Canada', 'Other region', 'New Glasgow'),
  ('Canada', 'Other region', 'New Westminster'),
  ('Canada', 'Other region', 'Niagara Falls'),
  ('Canada', 'Other region', 'North Bay'),
  ('Canada', 'Other region', 'North Vancouver'),
  ('Canada', 'Other region', 'Oakville'),
  ('Canada', 'Other region', 'Okotoks'),
  ('Canada', 'Other region', 'Orangeville'),
  ('Canada', 'Other region', 'Orillia'),
  ('Canada', 'Other region', 'Oshawa'),
  ('Canada', 'Other region', 'Ottawa'),
  ('Canada', 'Other region', 'Owen Sound'),
  ('Canada', 'Other region', 'Parksville'),
  ('Canada', 'Other region', 'Pembroke'),
  ('Canada', 'Other region', 'Penticton'),
  ('Canada', 'Other region', 'Peterborough'),
  ('Canada', 'Other region', 'Pickering'),
  ('Canada', 'Other region', 'Port Alberni'),
  ('Canada', 'Other region', 'Port Coquitlam'),
  ('Canada', 'Other region', 'Port Moody'),
  ('Canada', 'Other region', 'Portage la Prairie'),
  ('Canada', 'Other region', 'Powell River'),
  ('Canada', 'Other region', 'Prince Albert'),
  ('Canada', 'Other region', 'Prince George'),
  ('Canada', 'Other region', 'Prince Rupert'),
  ('Canada', 'Other region', 'Québec City'),
  ('Canada', 'Other region', 'Quesnel'),
  ('Canada', 'Other region', 'Quinte West'),
  ('Canada', 'Other region', 'Red Deer'),
  ('Canada', 'Other region', 'Regina'),
  ('Canada', 'Other region', 'Repentigny'),
  ('Canada', 'Other region', 'Richmond'),
  ('Canada', 'Other region', 'Richmond Hill'),
  ('Canada', 'Other region', 'Rimouski'),
  ('Canada', 'Other region', 'Rivière-du-Loup'),
  ('Canada', 'Other region', 'Rouyn-Noranda'),
  ('Canada', 'Other region', 'Saguenay'),
  ('Canada', 'Other region', 'Saint John'),
  ('Canada', 'Other region', 'Saint-Bruno-de-Montarville'),
  ('Canada', 'Other region', 'Saint-Constant'),
  ('Canada', 'Other region', 'Saint-Eustache'),
  ('Canada', 'Other region', 'Saint-Georges'),
  ('Canada', 'Other region', 'Saint-Hyacinthe'),
  ('Canada', 'Other region', 'Saint-Jean-sur-Richelieu'),
  ('Canada', 'Other region', 'Saint-Jérôme'),
  ('Canada', 'Other region', 'Saint-Lambert'),
  ('Canada', 'Other region', 'Sainte-Julie'),
  ('Canada', 'Other region', 'Salmon Arm'),
  ('Canada', 'Other region', 'Sarnia'),
  ('Canada', 'Other region', 'Saskatoon'),
  ('Canada', 'Other region', 'Sault Ste. Marie'),
  ('Canada', 'Other region', 'Selkirk'),
  ('Canada', 'Other region', 'Sept-Îles'),
  ('Canada', 'Other region', 'Sherbrooke'),
  ('Canada', 'Other region', 'Spruce Grove'),
  ('Canada', 'Other region', 'St. Albert'),
  ('Canada', 'Other region', 'St. Catharines'),
  ('Canada', 'Other region', 'St. John’s'),
  ('Canada', 'Other region', 'St. Thomas'),
  ('Canada', 'Other region', 'Steinbach'),
  ('Canada', 'Other region', 'Stratford'),
  ('Canada', 'Other region', 'Surrey'),
  ('Canada', 'Other region', 'Swift Current'),
  ('Canada', 'Other region', 'Sydney'),
  ('Canada', 'Other region', 'Terrace'),
  ('Canada', 'Other region', 'Terrebonne'),
  ('Canada', 'Other region', 'Thetford Mines'),
  ('Canada', 'Other region', 'Thompson'),
  ('Canada', 'Other region', 'Thunder Bay'),
  ('Canada', 'Other region', 'Timmins'),
  ('Canada', 'Other region', 'Toronto'),
  ('Canada', 'Other region', 'Trail'),
  ('Canada', 'Other region', 'Trois-Rivières'),
  ('Canada', 'Other region', 'Val-d’Or'),
  ('Canada', 'Other region', 'Vancouver'),
  ('Canada', 'Other region', 'Vaughan'),
  ('Canada', 'Other region', 'Vernon'),
  ('Canada', 'Other region', 'Victoria'),
  ('Canada', 'Other region', 'Waterloo'),
  ('Canada', 'Other region', 'Welland'),
  ('Canada', 'Other region', 'West Kelowna'),
  ('Canada', 'Other region', 'White Rock'),
  ('Canada', 'Other region', 'Whitehorse'),
  ('Canada', 'Other region', 'Williams Lake'),
  ('Canada', 'Other region', 'Windsor'),
  ('Canada', 'Other region', 'Winkler'),
  ('Canada', 'Other region', 'Winnipeg'),
  ('Canada', 'Other region', 'Woodstock'),
  ('Canada', 'Other region', 'Yellowknife'),
  ('United States', 'Other region', 'New York'),
  ('United States', 'Other region', 'Los Angeles'),
  ('United States', 'Other region', 'Chicago'),
  ('United States', 'Other region', 'Houston'),
  ('United States', 'Other region', 'Phoenix'),
  ('United States', 'Other region', 'Philadelphia'),
  ('United States', 'Other region', 'San Antonio'),
  ('United States', 'Other region', 'San Diego'),
  ('United States', 'Other region', 'Dallas'),
  ('United States', 'Other region', 'Austin'),
  ('United States', 'Other region', 'San Francisco'),
  ('United States', 'Other region', 'Seattle'),
  ('United States', 'Other region', 'Boston'),
  ('United States', 'Other region', 'Miami'),
  ('United States', 'Other region', 'Washington'),
  ('Mexico', 'Other region', 'Mexico City'),
  ('Mexico', 'Other region', 'Guadalajara'),
  ('Mexico', 'Other region', 'Monterrey'),
  ('Mexico', 'Other region', 'Puebla'),
  ('Mexico', 'Other region', 'Tijuana'),
  ('Brazil', 'Other region', 'São Paulo'),
  ('Brazil', 'Other region', 'Rio de Janeiro'),
  ('Brazil', 'Other region', 'Brasília'),
  ('Brazil', 'Other region', 'Salvador'),
  ('Brazil', 'Other region', 'Recife'),
  ('United Kingdom', 'Other region', 'London'),
  ('United Kingdom', 'Other region', 'Birmingham'),
  ('United Kingdom', 'Other region', 'Manchester'),
  ('United Kingdom', 'Other region', 'Glasgow'),
  ('United Kingdom', 'Other region', 'Edinburgh'),
  ('France', 'Other region', 'Paris'),
  ('France', 'Other region', 'Marseille'),
  ('France', 'Other region', 'Lyon'),
  ('France', 'Other region', 'Toulouse'),
  ('France', 'Other region', 'Nice'),
  ('France', 'Other region', 'Bordeaux'),
  ('Germany', 'Other region', 'Berlin'),
  ('Germany', 'Other region', 'Hamburg'),
  ('Germany', 'Other region', 'Munich'),
  ('Germany', 'Other region', 'Cologne'),
  ('Germany', 'Other region', 'Frankfurt'),
  ('Spain', 'Other region', 'Madrid'),
  ('Spain', 'Other region', 'Barcelona'),
  ('Spain', 'Other region', 'Valencia'),
  ('Spain', 'Other region', 'Seville'),
  ('Spain', 'Other region', 'Bilbao'),
  ('Italy', 'Other region', 'Rome'),
  ('Italy', 'Other region', 'Milan'),
  ('Italy', 'Other region', 'Naples'),
  ('Italy', 'Other region', 'Turin'),
  ('Italy', 'Other region', 'Florence'),
  ('Belgium', 'Other region', 'Brussels'),
  ('Belgium', 'Other region', 'Antwerp'),
  ('Belgium', 'Other region', 'Ghent'),
  ('Belgium', 'Other region', 'Liège'),
  ('Belgium', 'Other region', 'Bruges'),
  ('Switzerland', 'Other region', 'Zürich'),
  ('Switzerland', 'Other region', 'Geneva'),
  ('Switzerland', 'Other region', 'Basel'),
  ('Switzerland', 'Other region', 'Lausanne'),
  ('Switzerland', 'Other region', 'Bern'),
  ('Morocco', 'Other region', 'Casablanca'),
  ('Morocco', 'Other region', 'Rabat'),
  ('Morocco', 'Other region', 'Marrakesh'),
  ('Morocco', 'Other region', 'Tangier'),
  ('Morocco', 'Other region', 'Fez'),
  ('Algeria', 'Other region', 'Algiers'),
  ('Algeria', 'Other region', 'Oran'),
  ('Algeria', 'Other region', 'Constantine'),
  ('Algeria', 'Other region', 'Annaba'),
  ('Algeria', 'Other region', 'Blida'),
  ('Tunisia', 'Other region', 'Tunis'),
  ('Tunisia', 'Other region', 'Sfax'),
  ('Tunisia', 'Other region', 'Sousse'),
  ('Tunisia', 'Other region', 'Kairouan'),
  ('Tunisia', 'Other region', 'Bizerte'),
  ('Senegal', 'Other region', 'Dakar'),
  ('Senegal', 'Other region', 'Thiès'),
  ('Senegal', 'Other region', 'Saint-Louis'),
  ('Senegal', 'Other region', 'Rufisque'),
  ('Senegal', 'Other region', 'Ziguinchor'),
  ('Cameroon', 'Other region', 'Ngaoundéré'),
  ('Cameroon', 'Other region', 'Meiganga'),
  ('Cameroon', 'Other region', 'Banyo'),
  ('Cameroon', 'Other region', 'Tibati'),
  ('Cameroon', 'Other region', 'Tignère'),
  ('Cameroon', 'Other region', 'Yaoundé'),
  ('Cameroon', 'Other region', 'Mbalmayo'),
  ('Cameroon', 'Other region', 'Bafia'),
  ('Cameroon', 'Other region', 'Obala'),
  ('Cameroon', 'Other region', 'Mfou'),
  ('Cameroon', 'Other region', 'Nanga-Eboko'),
  ('Cameroon', 'Other region', 'Akonolinga'),
  ('Cameroon', 'Other region', 'Eséka'),
  ('Cameroon', 'Other region', 'Monatélé'),
  ('Cameroon', 'Other region', 'Ntui'),
  ('Cameroon', 'Other region', 'Bertoua'),
  ('Cameroon', 'Other region', 'Batouri'),
  ('Cameroon', 'Other region', 'Yokadouma'),
  ('Cameroon', 'Other region', 'Abong-Mbang'),
  ('Cameroon', 'Other region', 'Garoua-Boulaï'),
  ('Cameroon', 'Other region', 'Bélabo'),
  ('Cameroon', 'Other region', 'Kétté'),
  ('Cameroon', 'Other region', 'Lomié'),
  ('Cameroon', 'Other region', 'Maroua'),
  ('Cameroon', 'Other region', 'Kousséri'),
  ('Cameroon', 'Other region', 'Mokolo'),
  ('Cameroon', 'Other region', 'Yagoua'),
  ('Cameroon', 'Other region', 'Mora'),
  ('Cameroon', 'Other region', 'Kaélé'),
  ('Cameroon', 'Other region', 'Bogo'),
  ('Cameroon', 'Other region', 'Maga'),
  ('Cameroon', 'Other region', 'Waza'),
  ('Cameroon', 'Other region', 'Douala'),
  ('Cameroon', 'Other region', 'Nkongsamba'),
  ('Cameroon', 'Other region', 'Edéa'),
  ('Cameroon', 'Other region', 'Loum'),
  ('Cameroon', 'Other region', 'Manjo'),
  ('Cameroon', 'Other region', 'Melong'),
  ('Cameroon', 'Other region', 'Mbanga'),
  ('Cameroon', 'Other region', 'Dibombari'),
  ('Cameroon', 'Other region', 'Garoua'),
  ('Cameroon', 'Other region', 'Guider'),
  ('Cameroon', 'Other region', 'Figuil'),
  ('Cameroon', 'Other region', 'Pitoa'),
  ('Cameroon', 'Other region', 'Poli'),
  ('Cameroon', 'Other region', 'Lagdo'),
  ('Cameroon', 'Other region', 'Touboro'),
  ('Cameroon', 'Other region', 'Rey-Bouba'),
  ('Cameroon', 'Other region', 'Tcholliré'),
  ('Cameroon', 'Other region', 'Bamenda'),
  ('Cameroon', 'Other region', 'Kumbo'),
  ('Cameroon', 'Other region', 'Wum'),
  ('Cameroon', 'Other region', 'Nkambe'),
  ('Cameroon', 'Other region', 'Fundong'),
  ('Cameroon', 'Other region', 'Ndop'),
  ('Cameroon', 'Other region', 'Bali'),
  ('Cameroon', 'Other region', 'Bafut'),
  ('Cameroon', 'Other region', 'Batibo'),
  ('Cameroon', 'Other region', 'Mbengwi'),
  ('Cameroon', 'Other region', 'Ebolowa'),
  ('Cameroon', 'Other region', 'Kribi'),
  ('Cameroon', 'Other region', 'Sangmélima'),
  ('Cameroon', 'Other region', 'Ambam'),
  ('Cameroon', 'Other region', 'Lolodorf'),
  ('Cameroon', 'Other region', 'Akom II'),
  ('Cameroon', 'Other region', 'Djoum'),
  ('Cameroon', 'Other region', 'Zoétélé'),
  ('Cameroon', 'Other region', 'Meyomessala'),
  ('Cameroon', 'Other region', 'Buea'),
  ('Cameroon', 'Other region', 'Limbe'),
  ('Cameroon', 'Other region', 'Kumba'),
  ('Cameroon', 'Other region', 'Tiko'),
  ('Cameroon', 'Other region', 'Mamfe'),
  ('Cameroon', 'Other region', 'Muyuka'),
  ('Cameroon', 'Other region', 'Mutengene'),
  ('Cameroon', 'Other region', 'Bangem'),
  ('Cameroon', 'Other region', 'Mundemba'),
  ('Cameroon', 'Other region', 'Tombel'),
  ('Cameroon', 'Other region', 'Ekondo-Titi'),
  ('Cameroon', 'Other region', 'Bafoussam'),
  ('Cameroon', 'Other region', 'Dschang'),
  ('Cameroon', 'Other region', 'Foumban'),
  ('Cameroon', 'Other region', 'Mbouda'),
  ('Cameroon', 'Other region', 'Bafang'),
  ('Cameroon', 'Other region', 'Bangangté'),
  ('Cameroon', 'Other region', 'Foumbot'),
  ('Cameroon', 'Other region', 'Bandjoun'),
  ('Cameroon', 'Other region', 'Baham'),
  ('Cameroon', 'Other region', 'Tonga'),
  ('Cameroon', 'Other region', 'Batcham'),
  ('Côte d’Ivoire', 'Other region', 'Abidjan'),
  ('Côte d’Ivoire', 'Other region', 'Bouaké'),
  ('Côte d’Ivoire', 'Other region', 'Yamoussoukro'),
  ('Côte d’Ivoire', 'Other region', 'Daloa'),
  ('Côte d’Ivoire', 'Other region', 'San-Pédro'),
  ('Democratic Republic of the Congo', 'Other region', 'Kinshasa'),
  ('Democratic Republic of the Congo', 'Other region', 'Lubumbashi'),
  ('Democratic Republic of the Congo', 'Other region', 'Mbuji-Mayi'),
  ('Democratic Republic of the Congo', 'Other region', 'Goma'),
  ('Democratic Republic of the Congo', 'Other region', 'Kisangani'),
  ('Nigeria', 'Other region', 'Lagos'),
  ('Nigeria', 'Other region', 'Abuja'),
  ('Nigeria', 'Other region', 'Kano'),
  ('Nigeria', 'Other region', 'Ibadan'),
  ('Nigeria', 'Other region', 'Port Harcourt'),
  ('South Africa', 'Other region', 'Johannesburg'),
  ('South Africa', 'Other region', 'Cape Town'),
  ('South Africa', 'Other region', 'Durban'),
  ('South Africa', 'Other region', 'Pretoria'),
  ('South Africa', 'Other region', 'Soweto'),
  ('India', 'Other region', 'Mumbai'),
  ('India', 'Other region', 'Delhi'),
  ('India', 'Other region', 'Bengaluru'),
  ('India', 'Other region', 'Hyderabad'),
  ('India', 'Other region', 'Chennai'),
  ('China', 'Other region', 'Shanghai'),
  ('China', 'Other region', 'Beijing'),
  ('China', 'Other region', 'Shenzhen'),
  ('China', 'Other region', 'Guangzhou'),
  ('China', 'Other region', 'Chengdu'),
  ('Japan', 'Other region', 'Tokyo'),
  ('Japan', 'Other region', 'Yokohama'),
  ('Japan', 'Other region', 'Osaka'),
  ('Japan', 'Other region', 'Nagoya'),
  ('Japan', 'Other region', 'Sapporo'),
  ('Australia', 'Other region', 'Sydney'),
  ('Australia', 'Other region', 'Melbourne'),
  ('Australia', 'Other region', 'Brisbane'),
  ('Australia', 'Other region', 'Perth'),
  ('Australia', 'Other region', 'Adelaide'),
  ('New Zealand', 'Other region', 'Auckland'),
  ('New Zealand', 'Other region', 'Wellington'),
  ('New Zealand', 'Other region', 'Christchurch'),
  ('New Zealand', 'Other region', 'Hamilton'),
  ('New Zealand', 'Other region', 'Dunedin')
)
insert into public.cities(country_id, region_id, name)
select country.id, region.id, source.city_name
from source
join public.countries country
  on lower(btrim(country.name)) = lower(btrim(source.country_name))
join public.regions region
  on region.country_id = country.id
 and lower(btrim(region.name)) = lower(btrim(source.region_name))
on conflict do nothing;

update public.profiles profile
set residence_country_id = country.id
from public.countries country
where profile.residence_country_id is null
  and lower(btrim(country.name)) = lower(btrim(coalesce(
    profile.residence_country_name,
    profile.country_name
  )));

update public.profiles profile
set residence_region_id = region.id
from public.regions region
where profile.residence_region_id is null
  and region.country_id = profile.residence_country_id
  and lower(btrim(region.name)) = lower(btrim(profile.residence_region));

update public.profiles profile
set residence_city_id = city.id
from public.cities city
where profile.residence_city_id is null
  and city.country_id = profile.residence_country_id
  and city.region_id = profile.residence_region_id
  and lower(btrim(city.name)) = lower(btrim(coalesce(
    profile.residence_city,
    profile.city
  )));

update public.profiles profile
set origin_country_id = country.id
from public.countries country
where profile.origin_country_id is null
  and lower(btrim(country.name)) = lower(btrim(profile.origin_country_name));

update public.profiles profile
set origin_region_id = region.id
from public.regions region
where profile.origin_region_id is null
  and region.country_id = profile.origin_country_id
  and lower(btrim(region.name)) = lower(btrim(profile.origin_region));

update public.profiles profile
set origin_city_id = city.id
from public.cities city
where profile.origin_city_id is null
  and city.country_id = profile.origin_country_id
  and city.region_id = profile.origin_region_id
  and lower(btrim(city.name)) = lower(btrim(profile.origin_city));

update public.dating_preferences preference
set country_ids = coalesce((
      select array_agg(country.id order by choice.ordinality)
      from unnest(preference.country_codes) with ordinality choice(name, ordinality)
      join public.countries country
        on lower(btrim(country.name)) = lower(btrim(choice.name))
    ), '{}'::uuid[]);

update public.dating_preferences preference
set region_ids = coalesce((
      select array_agg(region.id order by choice.ordinality)
      from unnest(preference.regions) with ordinality choice(name, ordinality)
      join public.regions region
        on region.country_id = any(coalesce(preference.country_ids, '{}'::uuid[]))
       and lower(btrim(region.name)) = lower(btrim(choice.name))
    ), '{}'::uuid[]);

update public.dating_preferences preference
set city_ids = coalesce((
      select array_agg(city.id order by choice.ordinality)
      from unnest(preference.cities) with ordinality choice(name, ordinality)
      join public.cities city
        on city.region_id = any(coalesce(preference.region_ids, '{}'::uuid[]))
       and lower(btrim(city.name)) = lower(btrim(choice.name))
    ), '{}'::uuid[]);

update public.dating_preferences preference
set origin_country_ids = coalesce((
      select array_agg(country.id order by choice.ordinality)
      from unnest(preference.origin_country_names) with ordinality choice(name, ordinality)
      join public.countries country
        on lower(btrim(country.name)) = lower(btrim(choice.name))
    ), '{}'::uuid[]);

update public.dating_preferences preference
set origin_region_ids = coalesce((
      select array_agg(region.id order by choice.ordinality)
      from unnest(preference.origin_regions) with ordinality choice(name, ordinality)
      join public.regions region
        on region.country_id = any(coalesce(preference.origin_country_ids, '{}'::uuid[]))
       and lower(btrim(region.name)) = lower(btrim(choice.name))
    ), '{}'::uuid[]);

update public.dating_preferences preference
set origin_city_ids = coalesce((
      select array_agg(city.id order by choice.ordinality)
      from unnest(preference.origin_cities) with ordinality choice(name, ordinality)
      join public.cities city
        on city.region_id = any(coalesce(preference.origin_region_ids, '{}'::uuid[]))
       and lower(btrim(city.name)) = lower(btrim(choice.name))
    ), '{}'::uuid[]);

commit;
