-- A stable client id makes retries idempotent without comparing message text.
alter table public.messages
  add column if not exists client_message_id uuid;

create unique index if not exists messages_sender_client_id_unique
  on public.messages(sender_id, client_message_id);

comment on column public.messages.client_message_id is
  'Stable UUID generated by the client and reused when an upload or insert is retried.';
